"""empty message

Revision ID: 016d5a89d759
Revises: 1100cf85d9e0
Create Date: 2025-04-20 14:20:23.569951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '016d5a89d759'
down_revision: Union[str, None] = '1100cf85d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_amount', sa.Integer(), nullable=False),
    sa.Column('final_amount', sa.Integer(), nullable=False),
    sa.Column('pos_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iva', sa.Float(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traansaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_invoice', sa.Integer(), nullable=False),
    sa.Column('id_POS', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_POS'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['id_invoice'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('id_rol',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('id_rol',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('traansaction')
    op.drop_table('invoice')
    op.drop_table('pos')
    # ### end Alembic commands ###
