"""empty message

Revision ID: 19ab0ec1ee8c
Revises: ec614e4bbec4
Create Date: 2025-03-23 21:28:21.418046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '19ab0ec1ee8c'
down_revision: Union[str, None] = 'ec614e4bbec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
