"""empty message

Revision ID: 5e020f2455e8
Revises: f6fe7c231254
Create Date: 2025-03-23 12:32:03.939548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5e020f2455e8'
down_revision: Union[str, None] = 'f6fe7c231254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_customer', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'customer', ['id_customer'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_customer')

    # ### end Alembic commands ###
