"""empty message

Revision ID: 63ff5c8bed92
Revises: 6a8b7e5c5452
Create Date: 2025-04-28 20:26:07.582191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '63ff5c8bed92'
down_revision: Union[str, None] = '6a8b7e5c5452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('id_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('id_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
