"""empty message

Revision ID: 6a8b7e5c5452
Revises: d26f12cc0388
Create Date: 2025-04-28 20:24:41.087414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6a8b7e5c5452'
down_revision: Union[str, None] = 'd26f12cc0388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_order', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'order', ['id_order'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_order')

    # ### end Alembic commands ###
