"""empty message

Revision ID: c93ab6aa6415
Revises: 016d5a89d759
Create Date: 2025-04-20 14:22:12.917834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c93ab6aa6415'
down_revision: Union[str, None] = '016d5a89d759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traansaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_invoice', sa.Integer(), nullable=False),
    sa.Column('id_POS', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_POS'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['id_invoice'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traansaction')
    # ### end Alembic commands ###
