"""empty message

Revision ID: c9e5cf45ae02
Revises: 
Create Date: 2025-05-09 01:18:22.653157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c9e5cf45ae02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('id_rol',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_order', sa.Integer(), nullable=True))
        batch_op.drop_constraint('transaction_id_invoice_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['id_order'], ['id'])
        batch_op.drop_column('id_invoice')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_invoice', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_id_invoice_fkey', 'invoice', ['id_invoice'], ['id'])
        batch_op.drop_column('id_order')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('id_rol',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
