"""empty message

Revision ID: d26f12cc0388
Revises: 257dffb7ad28
Create Date: 2025-04-27 23:32:09.634753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd26f12cc0388'
down_revision: Union[str, None] = '257dffb7ad28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_id_invoice_fkey', type_='foreignkey')
        batch_op.drop_column('id_invoice')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_invoice', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('transaction_id_invoice_fkey', 'invoice', ['id_invoice'], ['id'])

    # ### end Alembic commands ###
