"""empty message

Revision ID: 9ff8be17a25c
Revises: bcf19e4b90b1
Create Date: 2025-05-10 00:05:33.656940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9ff8be17a25c'
down_revision: Union[str, None] = 'bcf19e4b90b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('ingredient_id_stock_fkey', type_='foreignkey')
        batch_op.drop_column('id_stock')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ingredient', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ingredient', ['id_ingredient'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_ingredient')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ingredient_id_stock_fkey', 'stock', ['id_stock'], ['id'])

    # ### end Alembic commands ###
