# .github/workflows/sonar.yml
name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    env:
      DB_USER:      ${{ secrets.DB_USER }}
      DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
      DB_HOST:      ${{ secrets.DB_HOST }}
      DB_PORT:      ${{ secrets.DB_PORT }}
      DB_NAME:      DellaSoft

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage          #  coverage>=7.0

      - name: Run tests & generate coverage.xml
        run: |
          # Ejecuta tests (si los hay). 5 ≙ “no tests collected”.
          coverage run -m pytest || true
          # Genera siempre coverage.xml; si coverage-xml falla devolvemos 0.
          coverage xml -i || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
